version: '3'
services:
  spring-app:
    container_name: spring-app
    build:
      context: ../BE
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"
    environment:
      MYSQL_HOST : mysql
      MYSQL_USER : root
      MYSQL_PASSWORD : ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    image: junyupk/backend

  react-app:
    container_name: react-app
    ports:
      - "3000:3000"
    build:
      context: ../FE
      dockerfile: ./Dockerfile
    image: junyupk/frontend
