server:
    port: 4000

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://i10a209.p.ssafy.io:3306/matdongsandb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
        username: root
        password: aktehdtksghkdlxld
    jpa:
        hibernate:
            ddl-auto: create
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                default_batch_fetch_size: 100
        defer-datasource-initialization: true
    sql:
        init:
            mode: always

    logging:
        level:
            org.hibernate.SQL : debug

